version: 0.2
env:
  variables:
    S3_BUCKET_ARN: "S3_BUCKET_ARN"
phases:
  install:
    commands:
      - echo Starting Install Stage
      - npm ci
      - npm run build && npm run export
  build:
    commands:
      - ./scripts/deploy-to-s3.sh ./out $S3_BUCKET_ARN